#! /usr/bin/python3

import sys
import random

def print_list(l) :
	output = ""
	for i in range (len(l) - 1) :
		output += str(l[i])
		output += " "
	output += str(l[len(l) - 1])
	print(output)

def generate_numbers(n) :
	l = []
	n = int(n)
	doublon = False
	while (len(l) < n) :
		nb = random.randrange(1, n + 1)
		for i in l :
			if (i == nb) :
				doublon = True
		if not doublon :
			l.append(nb)
		doublon = False
	print_list(l)


def main() :
	if (len(sys.argv) != 2) :
		print("Usage : python3 generate_numbers <range>")
		return (1)
	generate_numbers(sys.argv[1])
	return (0)

if (main() == 1) :
	exit (1)
exit (0)
